AWSTemplateFormatVersion: '2010-09-09'
Description: GatherQuiz RDSデータベース用CloudFormationテンプレート

Parameters:
  DbUser:
    Type: String
    Description: RDSデータベースのマスターユーザー名
    NoEcho: true
  DbPassword:
    Type: String
    Description: RDSデータベースのマスターパスワード
    NoEcho: true
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: リソースを起動するVPCのID
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: RDSデータベース用プライベートサブネットIDのリスト
  DbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: RDSデータベース用セキュリティグループのID

Resources:
  # RDS Database Subnet Group
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for GatherQuiz RDS
      SubnetIds: !Ref PrivateSubnetIds

  # RDS Database Instance
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${AWS::StackName}-db
      Engine: postgres
      EngineVersion: '15'
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: '20'
      MasterUsername: !Ref DbUser
      MasterUserPassword: !Ref DbPassword
      DBName: gatherquiz
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups:
        - !Ref DbSecurityGroupId

Outputs:
  DbEndpoint:
    Description: RDSデータベースのエンドポイント
    Value: !GetAtt DatabaseInstance.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-DbEndpoint
  DbPort:
    Description: RDSデータベースのポート番号
    Value: !GetAtt DatabaseInstance.Endpoint.Port
    Export:
      Name: !Sub ${AWS::StackName}-DbPort