ALTER TABLE "Tournament" ADD COLUMN "questionSlots" TEXT;
ALTER TABLE "Quiz" ADD COLUMN "label" TEXT;
ALTER TABLE "Quiz" ADD COLUMN "choiceCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Quiz" ADD COLUMN "choices" TEXT NOT NULL DEFAULT '[]';
