# See here for image contents: https://github.com/devcontainers/images/tree/main/src/typescript-node
ARG VARIANT="20-bookworm"
FROM mcr.microsoft.com/devcontainers/typescript-node:${VARIANT}

# Install pnpm
RUN npm install -g pnpm
